<?php

namespace Tests\Feature;

use App\Models\LocalDr;
use App\Models\Stf;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AutoGeneratedIdsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->actingAs(User::create([
            'name' => 'Test User',
            'email' => 'test@example.com',
            'password' => 'password123',
            'role' => 'medical_director',
        ]));
    }

    public function test_supplier_no_is_auto_generated_and_hidden_on_create(): void
    {
        $this->get('/suppliers/create')->assertOk()->assertDontSee(__('Supplier No *'));

        $this->post('/suppliers', ['Name' => 'First Supplier'])->assertRedirect('/suppliers');
        $this->assertDatabaseHas('Supplier', ['Suppl_No' => 'SUP01', 'Name' => 'First Supplier']);

        $this->post('/suppliers', ['Name' => 'Second Supplier'])->assertRedirect('/suppliers');
        $this->assertDatabaseHas('Supplier', ['Suppl_No' => 'SUP02', 'Name' => 'Second Supplier']);
    }

    public function test_clinic_no_is_auto_generated_and_hidden_on_create(): void
    {
        $this->get('/local-doctors/create')->assertOk()->assertDontSee(__('Clinic No *'));

        $this->post('/local-doctors', ['FirstName' => 'Greg', 'LastName' => 'House'])->assertRedirect('/local-doctors');
        $this->assertDatabaseHas('LocalDr', ['Clinic_No' => 'LD01', 'LastName' => 'House']);

        $this->post('/local-doctors', ['FirstName' => 'Lisa', 'LastName' => 'Cuddy'])->assertRedirect('/local-doctors');
        $this->assertDatabaseHas('LocalDr', ['Clinic_No' => 'LD02', 'LastName' => 'Cuddy']);
    }

    public function test_staff_no_continues_from_highest_existing_number(): void
    {
        Stf::create(['Stf_No' => 'S1009', 'FirstName' => 'Seed', 'LastName' => 'Staff']);

        $this->post('/staff', ['FirstName' => 'New', 'LastName' => 'Hire'])->assertRedirect('/staff');

        $this->assertDatabaseHas('Stf', ['Stf_No' => 'S1010', 'LastName' => 'Hire']);
    }

    public function test_supplier_and_doctor_nos_continue_from_existing_numbers(): void
    {
        Supplier::create(['Suppl_No' => 'SUP02', 'Name' => 'Seed Supplier']);
        LocalDr::create(['Clinic_No' => 'LD02', 'FirstName' => 'Seed', 'LastName' => 'Doctor']);

        $this->post('/suppliers', ['Name' => 'Next Supplier'])->assertRedirect('/suppliers');
        $this->assertDatabaseHas('Supplier', ['Suppl_No' => 'SUP03']);

        $this->post('/local-doctors', ['FirstName' => 'Next', 'LastName' => 'Doctor'])->assertRedirect('/local-doctors');
        $this->assertDatabaseHas('LocalDr', ['Clinic_No' => 'LD03']);
    }
}
