<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', __('Report')) — {{ __('WELLMEADOW Hospital') }}</title>
    <style>
        @page { size: A4; margin: 15mm 12mm; }
        * { box-sizing: border-box; }
        body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1e293b; font-size: 11pt; line-height: 1.5; margin: 0; background: #fff; }
        .report-header { border-bottom: 3px solid #112D6E; padding-bottom: 10px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; }
        .report-header h1 { margin: 0; font-size: 18pt; color: #112D6E; letter-spacing: -0.02em; }
        .report-header .subtitle { color: #64748b; font-size: 9pt; margin-top: 2px; }
        .report-meta { text-align: right; font-size: 9pt; color: #334155; line-height: 1.4; }
        .report-meta strong { color: #0f172a; }
        .report-footer { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 8px; font-size: 8pt; color: #94a3b8; display: flex; justify-content: space-between; }
        table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
        th { background: #f1f5f9; color: #475569; font-weight: 600; text-transform: uppercase; font-size: 7.5pt; letter-spacing: 0.05em; text-align: left; padding: 6px 8px; border-bottom: 1px solid #cbd5e1; }
        td { padding: 7px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        .badge { display: inline-block; padding: 1px 7px; border-radius: 9999px; font-size: 8pt; font-weight: 600; }
        .no-print { margin-bottom: 12px; }
        @media print {
            .no-print { display: none !important; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            a { color: inherit; text-decoration: none; }
        }
        @media screen {
            body { padding: 24px; max-width: 900px; margin: 0 auto; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="display:flex;justify-content:flex-end;gap:8px;">
        <a href="javascript:window.print()" style="background:#112D6E;color:#fff;padding:8px 16px;border-radius:8px;font-size:10pt;text-decoration:none;font-weight:600;">{{ __('Print') }} / {{ __('Save as PDF') }}</a>
        <a href="javascript:window.close()" style="background:#e2e8f0;color:#334155;padding:8px 16px;border-radius:8px;font-size:10pt;text-decoration:none;">{{ __('Close') }}</a>
    </div>

    <header class="report-header">
        <div>
            <h1>{{ __('WELLMEADOW Hospital') }}</h1>
            <div class="subtitle">@yield('report_subtitle', __('Clinical Report')) — @yield('report_context')</div>
        </div>
        <div class="report-meta">
            <div><strong>{{ __('Report date') }}:</strong> {{ \Carbon\Carbon::now()->format('d/m/Y H:i') }}</div>
            <div><strong>{{ __('Generated by') }}:</strong> {{ auth()->user()->name ?? 'System' }}</div>
            @hasSection('report_reference')
                <div><strong>{{ __('Reference') }}:</strong> @yield('report_reference')</div>
            @endif
            @yield('report_meta_extra')
        </div>
    </header>

    <main>
        @yield('content')
    </main>

    <footer class="report-footer">
        <span>{{ __('WELLMEADOW Hospital — Confidential') }}</span>
        <span>{{ __('Page') }} <span class="pageNumber"></span></span>
    </footer>
</body>
</html>
